import { api } from "@/lib/axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import { HomeProductCard } from "./components/homeProductCard";
import { HomePageStyles, ProductHomeStyles } from "./styles/homeStyle";
import { LeftNavbar } from "./components/leftNavbar";
// import { Roboto } from "next/font/google";

// const roboto = Roboto({});

export default function Home({ products }: { products: any[] }) {
  return (
    <>
      <Head>
        <title>Shop Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageStyles>
        <LeftNavbar />
        <div style={{ display: "flex" }}>
          {products.map((product) => (
            <div key={product.id}>
              <HomeProductCard 
                id={product.id}
                name={product.name}
                description={product.description}
                price={product.price}
                companyId={product.company_id}
                categoryId={product.category_id}
                stockAmount={product.stock_amount}
                discountPercentage={product.discount_percentage}
                isAvailable={product.is_available}
                photos={product.photos.length > 0 ? product.photos[0] : "https://res.cloudinary.com/dloadb2bx/image/upload/v1739210952/image-not-available_yli4h7.png"}
              />
            </div>
          ))}
        </div>
      </HomePageStyles>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const response = await api.get('/products');
    return {
      props: {
        products: response.data,
      },
    };
  } catch (error) {
    console.error('Error fetching products:', error);
    return {
      props: {
        products: [],
      },
    };
  }
}
